### ISSUE TITLE
What happened to NeutOS?

### ISSUE THREAD

**Issue by ImportTaste** [borntohonk/suppository#1]
C&D issues I assume?

**Comment by borntohonk** [comment]
> C&D issues I assume?

I was instructed by legal counsel to remove it as the C&D was vague enough that it and two other forks I had were indirectly "facilitating distribution", as it included offending items ("patches" circumventing software protection measures), or distributed it in one way or another.

NeutOS, a fork of nx-links to direct to "patch" repository, and a fork of aio-switch-updater that was made to target nx-links.

Had to remove all of it.
